# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

pod 'Fabric', '~> 1.3.0'
pod 'Fabric/Crashlytics', '~> 1.3.0'

target 'Unity-iPhone' do

end

target 'Unity-iPhone Tests' do

end
